Server:
  RunMode: debug
  Port: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  DefaultContextTimeout: 60
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  UserName: root
  Password: password
  Host: 192.168.0.123:3306
  DBName: mydb
  Charset: utf8mb4
  ParseTime: True
